Bunch of changes. Evolving rather quickly.

diff --git a/.local/bin/build-astyle b/.local/bin/build-astyle
--- a/.local/bin/build-astyle
+++ b/.local/bin/build-astyle
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Install the latest or specified version of astyle
 
@@ -25,17 +25,17 @@
 #-------------------------------------------------------------------------------
 # Make things more visible in the output
 
-REPORTING_BASH="$(dirname "$0")/reporting.bash"
-if [[ -f "${REPORTING_BASH}" ]]; then
-  # shellcheck source reporting.bash
-  source "${REPORTING_BASH}" "$0"
+SCRIPT="$(dirname "$0")/utils.bash"
+if [[ -x "${SCRIPT}" ]]; then
+  # shellcheck source=utils.bash
+  source "${SCRIPT}" "$0"
 else
-  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
+  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
 fi
 
 # Defaults
 #-------------------------------------------------------------------------------
-TOOL="astyle"
+TOOL_NAME="astyle"
 CLEAN=0
 DEBUG=0
 NPROC=4 # Cores to use when building
@@ -127,7 +127,7 @@ fi
 export CMAKE_INSTALL_PREFIX
 
 cd "${SRC}" || Die "Unable to enter ${SRC}"
-test "${CLEAN}" == 1 && rm -fr "${TOOL}*"
+test "${CLEAN}" == 1 && rm -fr "${TOOL_NAME}*"
 
 
 ###############################################################################
@@ -144,40 +144,47 @@ test "${CLEAN}" == 1 && rm -fr "${TOOL}*"
 FULL_VERS=${MAJVERS}.${MINVERS}
 ASTYLE_TARBALL="astyle_${FULL_VERS}_linux.tar.gz"
 URL="https://sourceforge.net/projects/astyle/files/astyle/astyle%20${FULL_VERS}/astyle_${FULL_VERS}_linux.tar.gz/download"
-echo "Fetching ${TOOL}"
+echo "Fetching ${TOOL_NAME}"
 if [[ "${TYPE}" == "-wget" ]]; then
   echo "% wget ${URL}"
-  wget "${URL}" || Die "Failed to download ${TOOL} from ${URL}"
+  wget "${URL}" || Die "Failed to download ${TOOL_NAME} from ${URL}"
 else
   echo "% curl -output ${ASTYLE_TARBALL} ${URL}"
-  curl -output "${ASTYLE_TARBALL}" "${URL}" || Die "Failed to download ${TOOL} from ${URL}"
+  curl -output "${ASTYLE_TARBALL}" "${URL}" || Die "Failed to download ${TOOL_NAME} from ${URL}"
 fi
-echo "Expanding ${TOOL} tarball"
+echo "Expanding ${TOOL_NAME} tarball"
 echo "% tar zxvf ${ASTYLE_TARBALL}"
 tar zxvf "${ASTYLE_TARBALL}" || Die "Failed to extract ${ASTYLE_TARBALL}"
-echo "% cd ${TOOL}"
-cd "${TOOL}" || Die "Unable to enter source directory"
+echo "% cd ${TOOL_NAME}"
+cd "${TOOL_NAME}" || Die "Unable to enter source directory"
 
-Info "Building ${TOOL}"
-BUILD_DIR="${TOOL}-build"
+Info "Building ${TOOL_NAME}"
+BUILD_DIR="${TOOL_NAME}-build"
 mkdir "${BUILD_DIR}" || Die "Unable to create ${BUILD_DIR} directory"
 cd "${BUILD_DIR}" || Die "Unable to enter ${BUILD_DIR} directory"
 cmake ..
 make
 
-Info "Installing ${TOOL}"
-echo "% make install"
-mv "${TOOL}" "${CMAKE_INSTALL_PREFIX}/bin/"
+if [[ -z "${NOINSTALL+x}" ]]; then
+  Info "Installing ${TOOL_NAME}"
+  echo "% make install"
+  mv "${TOOL_NAME}" "${CMAKE_INSTALL_PREFIX}/bin/"
 
-cd "${SRC}" || Die "Unable to enter source directory"
-if [[ "${CLEAN}" == 1 ]]; then
-  Info "Clean up"
-  rm -fr "${TOOL}"*
+  # Optional clean up
+  if [[ "${CLEAN}" == 1 ]]; then
+    Info "Clean up"
+    cd "${SRC}" || Die "Unable to enter source directory"
+    rm -fr "${TOOL_NAME}"*
+  fi
+
+  # Verify version installed
+  cd || Die "Unable to return to home"
+  "${TOOL_NAME}" --version
+
+  Info "Finished installing ${TOOL_NAME}"
+else
+  Info -mag "Stopped shy installing ${TOOL_NAME}"
 fi
 
-cd || Die "Unable to return to home"
-"${TOOL}" --version
-
-Info "Finished installing ${TOOL}"
 
 # vim:nospell
diff --git a/.local/bin/build-cmake b/.local/bin/build-cmake
--- a/.local/bin/build-cmake
+++ b/.local/bin/build-cmake
@@ -1,4 +1,4 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Install the latest or specified version of cmake
 
@@ -25,12 +25,12 @@
 #-------------------------------------------------------------------------------
 # Make things more visible in the output
 
-REPORTING_BASH="$(dirname "$0")/reporting.bash"
-if [[ -f "${REPORTING_BASH}" ]]; then
-  # shellcheck source reporting.bash
-  source "${REPORTING_BASH}" "$0"
+SCRIPT="$(dirname "$0")/utils.bash"
+if [[ -x "${SCRIPT}" ]]; then
+  # shellcheck source=utils.bash
+  source "${SCRIPT}" "$0"
 else
-  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
+  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
 fi
 
 # Defaults
diff --git a/.local/bin/build-systemc b/.local/bin/build-systemc
--- a/.local/bin/build-systemc
+++ b/.local/bin/build-systemc
@@ -1,6 +1,11 @@
 #!/usr/bin/env bash
 #
 # Steps to build and install SystemC
+TOOL_NAME="SystemC"
+TOOL_INFO="Go to 'https://accellera.org/downloads/standards/systemc' for more information."
+TOOL_SRC="systemc"
+TOOL_URL="https://github.com/accellera-official/systemc.git"
+TOOL_VERS=2.3.3
 
 #-------------------------------------------------------------------------------
 # The following is formatted for use with -help
@@ -48,59 +53,31 @@ fi
 SetupLogdir "$0"
 
 GetBuildOpts "$0" "$@"
+ConfirmBuildOpts || exit
 
-#-------------------------------------------------------------------------------
-# Environment variables - MODIFY TO SUITE YOUR NEEDS
-TARGET='systemc'
-GIT_URL="https://github.com/accellera-official/${TARGET}.git"
-VERSION_TAG=2.3.3
-SYSTEMC_HOME="${APPS}/${TARGET}" # <----- THIS IS WHERE INSTALLED VERSION GOES
-BUILD=build-cmake-"$(basename "${CC}")"
-CMAKE_INSTALL_PREFIX="${SYSTEMC_HOME}"
+Create_and_Cd "${SRC}"
+Info -grn "Obtaining ${TOOL_NAME} source"
+GetSource_and_Cd "${TOOL_SRC}" "${TOOL_URL}"
 
-export SYSTEMC_HOME
-export CMAKE_INSTALL_PREFIX CMAKE_CXX_STANDARD
-export BUILD CXX CC
+Info -grn "Compiling ${TOOL_NAME}"
+Generate "${GENERATOR}"
+_do make
+_do make check
 
-if [[ "${DEBUG}" == 1 ]]; then
-  Debug "BUILD=${BUILD}"
-  Debug "CC=${CC}"
-  Debug "CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
-  Debug "CMAKE_CXX_STANDARD=${CMAKE_CXX_STANDARD}"
-  Debug "CXX=${CXX}"
-  Debug "SRC=${SRC}"
-  Debug "SYSTEMC_HOME=${SYSTEMC_HOME}"
-  Debug
-fi
+if [[ -z "${NOINSTALL+x}" ]]; then
+  Info -grn "Installing ${TOOL_NAME} to final location"
+  _do make install
 
-#-------------------------------------------------------------------------------
-Info -grn "Obtaining SystemC source"
-cd "${SRC}" || Die "Unable to change into source directory '${SRC}'"
-if [[ -d "${TARGET}"/.git ]]; then
-  cd "${TARGET}" || Die "Unable to enter repo directory"
-  Do git pull
+  # Optional clean up
+  if [[ "${CLEAN}" == 1 ]]; then
+    Info "Clean up"
+    cd "${SRC}" || Die "Unable to enter source directory"
+    rm -fr "${TOOL_NAME}"*
+  fi
+
+  Info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
 else
-  # Download
-  Do git clone "${GIT_URL}" || Die "Unable to clone"
-  cd "${TARGET}" || Die "Unable to enter repo directory"
+  Info -mag "Stopped shy installing ${TOOL_NAME}"
 fi
-if [[ -s ${VERSION_TAG} ]]; then
-  Do git  checkout "${VERSION_TAG}"
-fi
-
-Info -grn "Compiling SystemC"
-Do rm -fr "${BUILD}"
-Do mkdir "${BUILD}" || Die "Unable to create build directory"
-cd "${BUILD}" || Die "Unable to enter ${BUILD} directory"
-Do cmake\
-   -DCMAKE_INSTALL_PREFIX="${CMAKE_INSTALL_PREFIX}"\
-   -DCMAKE_CXX_STANDARD="${CMAKE_CXX_STANDARD}"\
-   ..
-Do make
-Do make check
-Info -grn "Installing SystemC to final location"
-Do make install
-
-Info -grn "Finished installation of SystemC into ${SYSTEMC_HOME}"
 
 # vim:nospell
diff --git a/.local/bin/build-vim b/.local/bin/build-vim
--- a/.local/bin/build-vim
+++ b/.local/bin/build-vim
@@ -1,31 +1,55 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-# Build Vim from github clone and installs under ~/clone.
+# Script to build Vim from github and installs under ~/.local/.
+TOOL_NAME="Vi Improved (vim/gvim)"
+TOOL_INFO="Go to 'https://vim.org' for more information."
+TOOL_SRC="vim"
+TOOL_URL="https://github.com/vim/vim.git"
+GENERATOR="cmake"
 
-source reporting.bash "$0"
+function Realpath () {
+  /usr/bin/perl '-MCwd(abs_path)' -le "print abs_path(qq($*))"
+}
 
-SRC="${HOME}/.local/src"
-mkdir -p "${SRC}" || Die "Unable to create ${SRC}"
-cd "${HOME}/.local/src" || Die "Unable to enter source directory ${SRC}"
-git clone https://github.com/vim/vim.git || Die "Unable to fetch repo"
-cd ./vim || Die "Unable to enter repo"
-./configure --prefix ${HOME}/.local
-make
-make install
-cat <<'EOF'
+SCRIPT="$(dirname $(Realpath "$0"))/utils.bash"
+if [[ -x "${SCRIPT}" ]]; then
+  # shellcheck source=utils.bash
+  source "${SCRIPT}" "$0"
+else
+  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
+fi
+
+SetupLogdir "$0"
+
+GetBuildOpts "$0" "$@"
+ConfirmBuildOpts || exit
+
+Create_and_Cd "${SRC}"
+GetSource_and_Cd "${TOOL_SRC}" "${TOOL_URL}"
+
+Info "Configuring ${TOOL_NAME}"
+_do ./configure --prefix "${APPS}"
+Info "Making ${TOOL_NAME}"
+_do make
+Info "Installing ${TOOL_NAME}"
+_do make install
+
+Cleanup_Source "${TOOL_SRC}"
+
+IMPLEMENTATION=<<'EOF'
 -------------------------------------------------------------------------------
-* Built Vim under $HOME/.local/src/vim.
-* Installed Vim under $HOME/.local.
-* To use, prepend $HOME/.local/bin to your path appropriately.
-* For bash modify `.bashrc` by adding: `PATH="$HOME/.local/bin:$PATH"`
-* When satisfied, you may:
++ Built Vim under ${HOME}/.local/src/vim.
++ Installed Vim under ${HOME}/.local
++ To use, prepend ${HOME}/.local/bin to your path appropriately.
++ For bash modify `.bashrc` by adding: `PATH="${HOME}/.local/bin:$PATH"`
++ When satisfied, you may:
 
-  1. Clean-up the build directly with `cd $HOME/.local/src/vim && make clean`
+  1. Clean-up the build directly with `cd ${HOME}/.local/src/vim && make clean`
   - OR -
-  2. Remove Vim entirely with `rm -fr $HOME/.local/src/vim`
+  2. Remove Vim entirely with `rm -fr ${HOME}/.local/src/vim`
 
-* To share with others: `chmod a+x $HOME && chmod a+rx $HOME/.local`, and let
-  them know to add to `$HOME/.local/bin` to their paths.
++ To share with others: `chmod a+x ${HOME} && chmod a+rx ${HOME}/.local`, and let
+  them know to add to `${HOME}/.local/bin` to their paths.
 -------------------------------------------------------------------------------
 
 EOF
diff --git a/.local/tests/test-reporting b/.local/tests/test-reporting
--- a/.local/tests/test-reporting
+++ b/.local/tests/test-reporting
@@ -1,14 +1,14 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
-# A script to test the reporting.bash functions and provide an example of usage
+# A script to test the utils.bash functions and provide an example of usage
 
 BINDIR="$(realpath $(dirname "$0")/../bin)"
-REPORTING_BASH="${BINDIR}/reporting.bash"
-if [[ -f "${REPORTING_BASH}" ]]; then
-  # shellcheck source ../bin/reporting.bash
-  source "${REPORTING_BASH}" "$0"
+UTILS_BASH="${BINDIR}/utils.bash"
+if [[ -f "${UTILS_BASH}" ]]; then
+  # shellcheck source ../bin/utils.bash
+  source "${UTILS_BASH}" "$0"
 else
-  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
+  echo "Error: Missing ${UTILS_BASH}" 1>&2; exit 1
 fi
 
 echo xx "Testing Log; Echo; Info; Do; Ruler" xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
@@ -19,7 +19,7 @@ Info "Testing Info"
 Do "echo Testing Do"
 Info "Testing Ruler +; / Message; - Message"
 Do Ruler +
-Do Ruler / Hello there
+Do Ruler -grn / Hello there
 Do Ruler Hello there
 
 Ruler -cyn _ "Testing Pass; Fail; PassFail"
diff --git a/.local/tests/test-require b/.local/tests/test-require
--- a/.local/tests/test-require
+++ b/.local/tests/test-require
@@ -1,18 +1,16 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # A script to test Require
 
 BINDIR="$(realpath $(dirname "$0")/../bin)"
-REPORTING_BASH="${BINDIR}/reporting.bash"
-if [[ -f "${REPORTING_BASH}" ]]; then
-  # shellcheck source ../bin/reporting.bash
-  source "${REPORTING_BASH}" "$0"
+UTILS_BASH="${BINDIR}/utils.bash"
+if [[ -f "${UTILS_BASH}" ]]; then
+  # shellcheck source ../bin/utils.bash
+  source "${UTILS_BASH}" "$0"
 else
-  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
+  echo "Error: Missing ${UTILS_BASH}" 1>&2; exit 1
 fi
 
 Ruler -cyn _ "Testing Require & get-build-opts.bash"
-# shellcheck source=../bin/get-build-opts.bash
-Require get-build-opts.bash
 GetBuildOpts "$0" "$@"
 
