Variables renamed for clarity/consistency.
Signed-off-by: David C Black <david.black@doulos.com>

diff --git a/.local/bin/build-systemc b/.local/bin/build-systemc
--- a/.local/bin/build-systemc
+++ b/.local/bin/build-systemc
@@ -8,77 +8,91 @@ TOOL_BRIEF="build-systemc - build and install SystemC from github source"
 TOOL_NAME="SystemC"
 TOOL_INFO='Go to <https://accellera.org/downloads/standards/systemc> for more information.'
 # ${TOOL_SRC}/${TOOL_BASE} for full path to source
-TOOL_SRC=~/.local/src
+TOOL_SRC=${HOME}/.local/src
 TOOL_BASE="systemc"
 TOOL_URL="https://github.com/accellera-official/systemc.git"
 TOOL_VERS='3.0.1' # latest or 3.0 or 2.3.4
 TOOL_CHECKOUT=""
 
-export TOOL_BRIEF TOOL_NAME TOOL_SRC TOOL_BASE TOOL_URL TOOL_INFO TOOL_VERS TOOL_CHECKOUT TOOL_PATCHES
-export SYSTEMC_HOME TOOL_SRC BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX CMAKE_BUILD_TYPE CMAKE_APPLE_SILICON_PROCESSOR
+function Build_systemc()
+{
+    export TOOL_BRIEF TOOL_NAME TOOL_SRC TOOL_BASE TOOL_URL TOOL_INFO TOOL_VERS TOOL_CHECKOUT TOOL_PATCHES
+    export SYSTEMC_HOME BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX CMAKE_BUILD_TYPE CMAKE_APPLE_SILICON_PROCESSOR
+
+    # Search for the directory containing utils.bash
+    local SCRIPT_DIR
+    SCRIPT_DIR="$(Realpath "$(dirname "$1")"/../bin)"
+    if [[ ! -r "${SCRIPT_DIR}/utils.bash" ]]; then
+      SCRIPT_DIR="$(Realpath "${HOME}/.local/bin")"
+    fi
+    if [[ ! -r "${SCRIPT_DIR}/utils.bash" ]]; then
+      SCRIPT_DIR="$(Realpath "$(dirname "$1")")"
+    fi
+    if [[ ! -r "${SCRIPT_DIR}/utils.bash" ]]; then
+      printf "FATAL: Missing required source file '%s'\n" "${SCRIPT_DIR}/utils.bash"
+      exit 1
+    fi
+    shift
+
+    export UTILS_VERSION
+    # shellcheck disable=SC2250,SC1091
+    source "${SCRIPT_DIR}/utils.bash"
+
+    export LOGFILE
+    SetupLogdir "$0"
+    local SCRIPT_PATH
+    SCRIPT_PATH="$(Realpath "$0")"
+    Report_info -cyn "Executing ${SCRIPT_PATH} with utils.bash v${UTILS_VERSION}"
+
+    GetBuildOpts "$0" "$@"
+    CMAKE_INSTALL_PREFIX="${SYSTEMC_HOME}"
+    ConfirmBuildOpts || exit
+
+    Create_and_Cd "${TOOL_SRC}" || exit
+    Report_info -grn "Obtaining ${TOOL_NAME} source"
+    GetSource_and_Cd "${TOOL_BASE}" "${TOOL_URL}" || exit
+    Select_version "${TOOL_VERS}" || exit
+
+    Report_info -grn "Building ${TOOL_NAME}"
+    # shellcheck disable=SC2119,SC2312
+    Configure_tool | Log
+    # shellcheck disable=SC2119,SC2312
+    Compile_tool   | Log
+
+    if [[ -z "${NOINSTALL+x}" || "${NOINSTALL}" == "no" ]]; then
+      # shellcheck disable=SC2119,SC2312
+      Install_tool | Log
+
+      # Optional clean up
+      if [[ "${CLEAN}" == 1 ]]; then
+        Report_info -red "Clean up"
+        cd "${TOOL_SRC}" || Report_fatal "Unable to enter source directory"
+        # shellcheck disable=SC2312
+        rm -fr "${TOOL_NAME}"* | Log
+      fi
+
+      Report_info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
+    else
+      Report_info -mag "Stopped shy of installing ${TOOL_NAME}"
+    fi
+
+    # Clean up
+    if [[ -n "${TMP}" ]]; then
+      rm -fr "${TMP}"
+    fi
+    if [[ -r "${LOGFILE}" ]]; then
+      if [[ -z "${TOOL_VERS}" ]]; then
+        TOOL_VERS="default"
+      fi
+      mv "${LOGFILE}" "${LOGFILE/.log/}-${TOOL_VERS}.log"
+    fi
+}
 
 function Realpath() {
   if [[ $# == 0 ]]; then set - .; fi
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-SCRIPTDIR="$(Realpath "$(dirname "$0")"/../bin)"
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath ~/.local/bin)"
-fi
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath "$(dirname "$0")")"
-fi
-if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  printf "FATAL: Missing required source file '%s'\n" "${SCRIPTDIR}/utils.bash"
-  exit 1
-fi
-
-export UTILS_VERSION
-# shellcheck disable=SC2250,SC1091
-source "$SCRIPTDIR/utils.bash"
-
-export LOGFILE
-SetupLogdir "$0"
-SCRIPTPATH="$(Realpath "$0")"
-Report_info -cyn "Executing ${SCRIPTPATH} with utils.bash v${UTILS_VERSION}"
-
-GetBuildOpts "$0" "$@"
-CMAKE_INSTALL_PREFIX="${SYSTEMC_HOME}"
-ConfirmBuildOpts || exit
-
-Create_and_Cd "${TOOL_SRC}" || exit
-Report_info -grn "Obtaining ${TOOL_NAME} source"
-GetSource_and_Cd "${TOOL_BASE}" "${TOOL_URL}" || exit
-Select_version "${TOOL_VERS}" || exit
-
-Report_info -grn "Building ${TOOL_NAME}"
-# shellcheck disable=SC2119,SC2312
-Configure_tool | Log
-# shellcheck disable=SC2119,SC2312
-Compile_tool   | Log
-
-if [[ -z "${NOINSTALL+x}" || "${NOINSTALL}" == "no" ]]; then
-  # shellcheck disable=SC2119,SC2312
-  Install_tool | Log
-
-  # Optional clean up
-  if [[ "${CLEAN}" == 1 ]]; then
-    Report_info -red "Clean up"
-    cd "${TOOL_SRC}" || Report_fatal "Unable to enter source directory"
-    # shellcheck disable=SC2312
-    rm -fr "${TOOL_NAME}"* | Log
-  fi
-
-  Report_info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
-else
-  Report_info -mag "Stopped shy of installing ${TOOL_NAME}"
-fi
-if [[ -r "${LOGFILE}" ]]; then
-  if [[ -z "${TOOL_VERS}" ]]; then
-    TOOL_VERS="default"
-  fi
-  mv "${LOGFILE}" "${LOGFILE/.log/}-${TOOL_VERS}.log"
-fi
+Build_systemc "$0" "$@"
 
 # vim:nospell
diff --git a/.local/bin/git-alias b/.local/bin/git-alias
--- a/.local/bin/git-alias
+++ b/.local/bin/git-alias
@@ -2,10 +2,9 @@
 #
 # git-alias - List all or specified git aliases
 
-TOOLNAME=git-alias
+TOOL_NAME=git-alias
 VERSION=1.0
 
-#-------------------------------------------------------------------------------
 function Git_alias_help()
 {
   local HELPTEXT
@@ -14,19 +13,19 @@ function Git_alias_help()
 Name
 ----
 
-TOOLNAME (vVERSION) - create a directory archive.
+TOOL_NAME (vVERSION) - manipulate aliases
 
 Synopsis
 --------
 
 ```sh
-TOOLNAME --help
-TOOLNAME list [:sq:GLOB:sq:]
-TOOLNAME dump [:sq:GLOB:sq:]
-TOOLNAME show [:sq:GLOB:sq:]
-TOOLNAME add NAME :sq:VALUE:sq:
-TOOLNAME rm NAME
-TOOLNAME exists NAME
+TOOL_NAME help
+TOOL_NAME list [:sq:GLOB:sq:]
+TOOL_NAME dump [:sq:GLOB:sq:]
+TOOL_NAME show [:sq:GLOB:sq:]
+TOOL_NAME add NAME :sq:VALUE:sq:
+TOOL_NAME rm NAME
+TOOL_NAME exists NAME
 ```
 
 Options
@@ -34,11 +33,11 @@ Options
 
 | Option   | Aka | Description                   |
 | -------- | --- | ----------------------------- |
-| --help   | -h  | Display this text             |
+| help     | -h  | Display this text             |
 
 '
   HELPTEXT="$( Repl "${HELPTEXT}" ":sq:" "'" )"
-  HELPTEXT="$( Repl "${HELPTEXT}" "TOOLNAME" "${TOOLNAME}" )"
+  HELPTEXT="$( Repl "${HELPTEXT}" "TOOL_NAME" "${TOOL_NAME}" )"
   HELPTEXT="$( Repl "${HELPTEXT}" "VERSION"  "${VERSION}"  )"
   if builtin command -v glow; then
     glow -p <<<"${HELPTEXT}" ;#>>>
@@ -46,6 +45,27 @@ Options
     less <<<"${HELPTEXT}" ;#>>>
   fi
 };#endfunction Git_alias_help
+
+export DEBUG=0
+export ERROR_COUNT=0
+
+#-------------------------------------------------------------------------------
+Report_error() {
+  printf "\033[1;91mError:\033[0m %s\n" "$*"
+  (( ++ERROR_COUNT ))
+}
+
+#-------------------------------------------------------------------------------
+Report_warning() {
+  printf "\033[1;93mWarning:\033[0m %s\n" "$*"
+}
+
+#-------------------------------------------------------------------------------
+Report_debug() {
+  if [[ ${DEBUG} -gt 0 ]]; then
+    printf "\033[1;95mDebug:\033[0m %s\n" "$*"
+  fi
+}
 
 #-------------------------------------------------------------------------------
 function Repl()
@@ -57,66 +77,99 @@ function Repl()
 };#endfunction Repl
 
 #-------------------------------------------------------------------------------
+function Shift() { # Shift an array left
+  local -n arr_ref="$1" # reference variable
+  test ${#arr_ref[@]} = 0 && return 1; # nothing to shift
+  arr_ref=("${arr_ref[@]:1}")
+  return 0 # Indicate success
+}
+
+#-------------------------------------------------------------------------------
 function Git_alias()
 {
-  if [[ $# == 0 ]]; then
-    git config --get-regexp 'alias.*' | colrm 1 6 | sed -e 's/ .*//' | fmt | table || true
-  else
-    local ACTION="list"
-    local OUT ALIAS
-    while [[ $# -gt 0 ]]; do
-      case "$1" in
-        --help|-help|-h|help)
-          Git_alias_help
-          return 0
-          ;;
-        list|show|add|rm|exists) ACTION="-$1" ;;
-        dump)
-          if [[ $# == 0 ]]; then
-            mapfile -t OUT < <(git config --global --get-regexp "alias." || true)
-            for ALIAS in "${OUT[@]}"; do
-              printf "%s\n" "${ALIAS}"
-            done
-          else
-            ACTION="-dump"
-          fi
-          ;;
-        *)
-          case "${ACTION}" in
-            -exists)
-              # shellcheck disable=SC2312
-              git config --global --get-regexp "alias.$1" | grep -q "$1" && return 0 || return 1
-              ;;
-            -list)
-              git config --global --get-regexp "alias.$1" | perl -pe 's/^alias\.//;s/ .*//' | fmt || true
-              ;;
-            -dump)
-              mapfile -t OUT < <(git config --global --get-regexp "alias.$1" || true)
-              for ALIAS in "${OUT[@]}"; do
-                printf "%s => \n" "${ALIAS}"
-              done
-              ;;
-            -add)
-              git config --global --add "alias.$1" "$2" && printf "\033[1;96mAdded %s\033[0m\n" "$1"
-              shift
-              ;;
-            -rm)
-              git config --global --unset "alias.$1" && printf "\033[1;96mRemoved %s\033[0m\n" "$1"
-              ;;
-            -show)
-              mapfile -t OUT < <(git config --global --get "alias.$1" || true)
-              if [[ -n "${OUT[*]}" ]]; then
-                printf "%s => %s\n" "$1" "${OUT[*]}"
-              fi
-              ;;
-            *)
-              set - "nop" "show" "$@"
-              ;;
-          esac
-      esac
-      shift
-    done
+  local -a ARGS
+  read -ra ARGS <<<"$*"
+  local ACTION="-list" ;#< default action
+  local OUT ALIAS OPT ARG1 ARG2
+  if [[ ${#ARGS[@]} == 0 ]]; then
+    ARGS=( "list" )
   fi
+  while [[ ${#ARGS[@]} -gt 0 ]]; do
+    OPT="${ARGS[0]}"; Shift ARGS
+    Report_debug "action=${ACTION} opt = ${OPT}"
+    case "${OPT}" in
+      -help|-h|help)
+        Git_alias_help
+        return 0
+        ;;
+      --debug|-D)
+        DEBUG=1
+        Report_debug "Debugging ${TOOL_NAME}"
+        if [[ ${#ARGS} == 0 ]]; then
+          ARGS=( "list" )
+        fi
+        ;;
+      --nodebug)
+        DEBUG=0
+        Report_debug "Debugging off"
+        ;;
+      list|show|add|rm|exists|dump)
+        ACTION="-${OPT}"
+        ARGS=( "${ACTION}" "${ARGS[@]}" )
+        ;;
+      -exists)
+        if [[ ${#ARGS[@]} -lt 1 ]]; then Report_error "${ACTION} requires 1 argument"; break; fi
+        ARG1="${ARGS[0]}"; Shift ARGS
+        # shellcheck disable=SC2312
+        git config --global --get-regexp "alias.${ARG1}" |\
+         grep -q "${ARG1}" && return 0 || return 1
+        ;;
+      -list)
+        if [[ ${#ARGS[@]} -lt 1 ]]; then
+          git config --global --get-regexp "alias.*" |\
+           colrm 1 6 | sed -e 's/ .*//' | fmt | table || true
+        else
+          ARG1="${ARGS[0]}"; Shift ARGS
+          Report_debug "ARG1=${ARG1}"
+          git config --global --get-regexp "alias.${ARG1}*" |\
+           perl -pe 's/^alias\.//;s/ .*//' |\
+           colrm 1 6 | sed -e 's/ .*//' | fmt | table || true
+        fi
+        ;;
+      -dump)
+        if [[ ${#ARGS[@]} -lt 1 ]]; then Report_error "${ACTION} requires 1 argument"; break; fi
+        ARG1="${ARGS[0]}"; Shift ARGS
+        mapfile -t OUT < <(git config --global --get-regexp "alias.${ARG1}" || true)
+        for ALIAS in "${OUT[@]}"; do
+          printf "%s => %s\n" "${ARG1}" "${ALIAS}"
+        done
+        ;;
+      -add)
+        if [[ ${#ARGS[@]} -lt 2 ]]; then Report_error "${ACTION} requires at least two arguments"; break; fi
+        ARG1="${ARGS[0]}"; Shift ARGS
+        ARG2="${ARGS[*]}"; shift
+        git config --global --add "alias.${ARG1}" "${ARG2}" && printf "\033[1;96mAdded %s\033[0m\n" "$1"
+        shift
+        ;;
+      -rm)
+        if [[ ${#ARGS[@]} -lt 1 ]]; then Report_error "${ACTION} requires 1 argument"; break; fi
+        ARG1="${ARGS[0]}"; Shift ARGS
+        git config --global --unset "alias.${ARG1}" && printf "\033[1;96mRemoved %s\033[0m\n" "${ARG1}"
+        ;;
+      -show)
+        if [[ ${#ARGS[@]} -lt 1 ]]; then Report_error "${ACTION} requires 1 argument"; break; fi
+        ARG1="${ARGS[0]}"; Shift ARGS
+        mapfile -t OUT < <(git config --global --get "alias.${ARG1}" || true)
+        if [[ -n "${OUT[*]}" ]]; then
+          printf "%s => %s\n" "${ARG1}" "${OUT[*]}"
+        fi
+        ;;
+      *)
+        Report_error "Unknown option ${OPT}"
+        break
+        ;;
+    esac
+  done
 };#endfunction Git_alias
 
 Git_alias "$@"
