Fix return status from logged files

diff --git a/.local/bin/build b/.local/bin/build
--- a/.local/bin/build
+++ b/.local/bin/build
@@ -3,7 +3,7 @@
 #
 # $Info: build version 1.0 $
 
-function Die() { echo "FAILED to build! $*" 1>&2; return 1; }
+function Die() { echo "FAILED to build! $*" 1>&2; exit 1; }
 
 function Build-help()
 {
@@ -103,8 +103,7 @@ function Build()
       exec "${UTILITY}" "$@"
       return 0
     else
-      Report_fatal "No build script found to build specified library or tool named ${UTILITY}"
-      return 0
+      Report_fatal "No build script found to build specified library or tool named ${UTILITY}" ; exit 1
     fi
   fi
   if [[ "$*" =~ ^-{1,2}list-extensions$ || "$*" == "-lx" ]]; then
@@ -114,18 +113,34 @@ function Build()
     exit 0
   fi
 
+  export SCRIPTS_DIR
+  # If not yet defined
+  if [[ -z "${SCRIPTS_DIR}" ]]; then
+    # Try the directory where build is located
+    SCRIPTS_DIR="$(dirname "$0")"
+  fi
+  if [[ ! -f "${SCRIPTS_DIR}/Essential-IO" ]]; then
+    # Try home installation
+    SCRIPTS_DIR="${HOME}/.local/scripts"
+  fi
+  if [[ ! -f "${SCRIPTS_DIR}/Essential-IO" ]]; then
+    Die "Unable to find Essential-IO in ${SCRIPTS_DIR}"
+  fi
+  # shellcheck disable=SC1091
+  source "${SCRIPTS_DIR}/Essential-IO"
+
   # Add .buildrc if present
   #------------------------------------------------------------------------------
   if [[ ! "$*" =~ norc ]]; then
     local -a BUILDRC
     if [[ -r "${HOME}/.buildrc" ]]; then
-      BUILDRC+=( "$(cat "${HOME}/.buildrc")" "$@"  )
+      BUILDRC+=( "$(cat "${HOME}/.buildrc")" )
     fi
     if [[ -r "./.buildrc" ]]; then
-      BUILDRC+=( "$(cat "./.buildrc")" "$@"  )
+      BUILDRC+=( "$(cat "./.buildrc")" )
     fi
-    if [[ ${#BUILDRC[@]} != 0 ]]; then
-      set "${BUILDRC[@]}"
+    if [[ ${#BUILDRC[@]} -gt 0 ]]; then
+      set - "${BUILDRC[@]}" "$@"
     fi
   fi
 
@@ -150,22 +165,6 @@ function Build()
   BUILD_LOG=build.log
   BUILD_OPTS=()
   TEST_OPTS=()
-
-  export SCRIPTS_DIR
-  # If not yet defined
-  if [[ -z "${SCRIPTS_DIR}" ]]; then
-    # Try the directory where build is located
-    SCRIPTS_DIR="$(dirname "$0")"
-  fi
-  if [[ ! -f "${SCRIPTS_DIR}/Essential-IO" ]]; then
-    # Try home installation
-    SCRIPTS_DIR="${HOME}/.local/scripts"
-  fi
-  if [[ ! -f "${SCRIPTS_DIR}/Essential-IO" ]]; then
-    Die "Unable to find Essential-IO in ${SCRIPTS_DIR}"
-  fi
-  # shellcheck disable=SC1091
-  source "${SCRIPTS_DIR}/Essential-IO"
   Logfile "${BUILD_LOG}"
   Log "% $0 $*"
 
@@ -179,28 +178,28 @@ function Build()
       Build-help; return 0
     elif [[ "$1" == "-B" ]]; then
       if [[ $# -lt 2 ]]; then
-        Report_error "-B requires a directory argument"
+        Report_fatal "-B requires a directory argument" ; exit 1
       else
         BLD_DIR="$2"
         shift
       fi
     elif [[ "$1" == "-C" ]]; then
       if [[ $# -lt 2 ]]; then
-        Report_error "-C requires a directory argument"
+        Report_fatal "-C requires a directory argument" ; exit 1
       elif [[ ! -d "$2" ]]; then
-        Report_error "'$2' is not a directory as required by -C"
+        Report_fatal "'$2' is not a directory as required by -C" ; exit 1
       else
         if ! cd "$2"; then
-          Report_error "Failed to change directory!?"; return 1;
+          Report_fatal "Failed to change directory!?"; exit 1;
         fi
         SUBPROJ_DIR="$(pwd)"
         shift
       fi
     elif [[ "$1" == "-P" ]]; then
       if [[ $# -lt 2 ]]; then
-        Report_error "-P requires a directory argument"
+        Report_fatal "-P requires a directory argument" ; exit 1
       elif [[ ! -d "$2" ]]; then
-        Report_error "'$2' is not a directory as required by -P"
+        Report_fatal "'$2' is not a directory as required by -P" ; exit 1
       else
         WORKTREE_DIR="$2"
         if [[ ! -d "$2/.git" ]]; then
@@ -210,9 +209,9 @@ function Build()
       fi
     elif [[ "$1" == "-S" ]]; then
       if [[ $# -lt 2 ]]; then
-        Report_error "-S requires a directory argument"
+        Report_fatal "-S requires a directory argument" ; exit 1
       elif [[ ! -d "$2" ]]; then
-        Report_error "'$2' is not a directory as required by -S"
+        Report_fatal "'$2' is not a directory as required by -S" ; exit 1
       else
         SRC_DIR="$2"
         shift
@@ -242,7 +241,7 @@ function Build()
       PREFIX="$2"
       if [[ ! -d "${PREFIX}" ]]; then
         PREFIX=""
-        Report_error "--prefix must be followed by a valid installation directory"; return 1;
+        Report_fatal "--prefix must be followed by a valid installation directory" ; exit 1
       else
         shift
       fi
@@ -283,14 +282,11 @@ function Build()
   # Validate environment
   #-------------------------------------------------------------------------------
   if [[ ! -r CMakeLists.txt ]]; then
-    Report_error "Missing CMakeLists.txt!"
-    return 1
+    Report_fatal "Missing CMakeLists.txt!" ; exit 1
   elif ! grep '^cmake_minimum_required' CMakeLists.txt; then
-    Report_error "CMakeLists.txt missing cmake_minimum_required directive -- are you in the right directory?"
-    return 1
+    Report_fatal "CMakeLists.txt missing cmake_minimum_required directive -- are you in the right directory?" ; exit 1
   elif ! grep '^project' CMakeLists.txt; then
-    Report_error "CMakeLists.txt missing project directive -- are you in the right directory?"
-    return 1
+    Report_fatal "CMakeLists.txt missing project directive -- are you in the right directory?" ; exit 1
   fi
 
   # shellcheck disable=SC2016
@@ -343,22 +339,23 @@ function Build()
   Report_info "Configuring ${SUBPROJ_DIR}"
   if [[ -z "${DEBUG}" ]]; then
     if [[ -z "${CMAKE_PREFIX_PATH}" ]]; then
-      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" || return 1
+      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" || exit 1
     else
-      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" || return 1
+      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" || exit 1
     fi
   else
     if [[ -z "${CMAKE_PREFIX_PATH}" ]]; then
-      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" "${DEBUG}" || return 1
+      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" "${DEBUG}" || exit 1
     else
-      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" "${DEBUG}" || return 1
+      _do cmake -S "${SRC_DIR}" -B "${BLD_DIR}" -DCMAKE_PREFIX_PATH="${CMAKE_PREFIX_PATH}" -DCMAKE_BUILD_TYPE="${CMAKE_BUILD_TYPE}" "${DEBUG}" || exit 1
     fi
   fi
 
   #------------------------------------------------------------------------------
   Report_info "Compiling ${SUBPROJ_DIR}"
   # shellcheck disable=SC2086
-  _do cmake --build "${BLD_DIR}" --config "${CMAKE_BUILD_TYPE}" "${BUILD_OPTS[@]}" || return 1
+  _do cmake --build "${BLD_DIR}" --config "${CMAKE_BUILD_TYPE}" "${BUILD_OPTS[@]}"
+  if [[ $? != 0 ]]; then exit 1; fi
 
   #------------------------------------------------------------------------------
   if [[ "${ACTION}" == gdb ]]; then
@@ -366,35 +363,35 @@ function Build()
     if [[ -n "${TARGETS}" ]]; then
       for EXECUTABLE in ${TARGETS}; do
         # shellcheck disable=SC2086,SC2312
-        ( _do gdb "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" || return 1 )
+        ( _do gdb "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" )
       done
     else
-      Report_error "Not sure what to debug!"
+      Report_fatal "Not sure what to debug!" 
     fi
   elif [[ "${ACTION}" == lldb ]]; then
     Report_info "Debugging ${SUBPROJ_DIR}"
     if [[ -n "${TARGETS}" ]]; then
       for EXECUTABLE in ${TARGETS}; do
         # shellcheck disable=SC2086,SC2312
-        ( _do lldb "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" || return 1 )
+        ( _do lldb "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" )
       done
     else
-      Report_error "Not sure what to debug!"
+      Report_fatal "Not sure what to debug!" 
     fi
   elif [[ "${ACTION}" == run ]]; then
     Report_info "Running ${SUBPROJ_DIR}"
     if [[ -n "${TARGETS}" ]]; then
       for EXECUTABLE in ${TARGETS}; do
         # shellcheck disable=SC2086,SC2312
-        ( _do "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" || return 1 ) 2>&1 | tee run.log
+        ( _do "${BLD_DIR}/${EXECUTABLE}" "${TEST_OPTS[@]}" ) 2>&1 | tee run.log
       done
     else
-      Report_error "Not sure what to run! Probably sub-directories. Please run manually. Look for executable under build."
+      Report_fatal "Not sure what to run! Probably sub-directories. Please run manually. Look for executable under build." 
     fi
   elif [[ "${ACTION}" == test ]]; then
     Report_info "Testing ${SUBPROJ_DIR}"
     # shellcheck disable=SC2086,SC2312
-    ( _do ctest --test-dir "${BLD_DIR}" -C "${CMAKE_BUILD_TYPE}" "${TEST_OPTS[@]}" || return 1 ) 2>&1 | tee test.log
+    ( _do ctest --test-dir "${BLD_DIR}" -C "${CMAKE_BUILD_TYPE}" "${TEST_OPTS[@]}" ) 2>&1 | tee test.log
   elif [[ -x "${BLD_DIR}/${EXECUTABLE}" ]]; then
     if grep -q add_test CMakeLists.txt; then
       Report_info "Executable is in ${BLD_DIR}/${EXECUTABLE} -- HINT: Next time try adding -test but in the meantime try:"
