Build in externs/ directory
Signed-off-by: David C Black <david.black@doulos.com>

diff --git a/.local/bin/build-fmt b/.local/bin/build-fmt
--- a/.local/bin/build-fmt
+++ b/.local/bin/build-fmt
@@ -1,75 +1,41 @@
 #!/usr/bin/env bash
 #
-# Script to build and install fmtlib (useful prior to C++20)
-TOOL_NAME="C++ formatting library (fmt)"
-TOOL_INFO="Go to https://fmt.dev/latest/index.html for more information."
-TOOL_SRC='fmt'
-TOOL_URL="https://github.com/fmtlib/fmt.git"
-GENERATOR="cmake"
+# Install {fmt} library under current project.
+# IMPORTANT; Must be run inside project git repository.
 
-#-------------------------------------------------------------------------------
-# The following is formatted for use with -help
-#|
-#|NAME
-#|----
-#|
-#|  $0 - build and install fmtlib from github source
-#|
-#|SYNOPSIS
-#|--------
-#|
-#|  $0 -help
-#|  $0 [OPTIONS...]
-#|
-#|DESCRIPTION
-#|-----------
-#|
-#|  Downloads, unpacks, builds and installs the latest or specified version of fmtlib.
-#|
-#|OPTIONS
-#|-------
-#|
-#|  Option             |  Alternative      | Description
-#|  ------             |  ------------     | -----------
-#|  --cc=C_COMPILER    |  CC=C_COMPILER    | chooses C compiler executable
-#|  --clang            |                   | quick --cc=clang --cxx=clang++
-#|  --cxx=CPP_COMPILER |  CXX=CPP_COMPILER | chooses C++ compiler executable
-#|  --debug            |                   | developer use
-#|  --default          |                   | quick -i=$HOME/.local -src=$HOME/.local/src
-#|  --gcc              |                   | quick --cc=gcc --cxx=g++
-#|  --home             |                   | quick -i $HOME -s $HOME/src
-#|  --install=DIR      |  -i DIR           | choose installation directory
-#|  --src=DIR          |  -s DIR           | choose source directory
-#|  --std=N            |  -std=N           | set make C++ compiler version where N={98,11,14,17,20,...}
-#|  --suffix=TEXT      |  -suf TEXT        | set suffix for installation name
-#|
+LIBNAME="{fmt} library"
+GIT_URL="https://github.com/fmtlib/fmt.git"
 
+function Die() {
+  echo "FAILED to build and install ${LIBNAME}! $*" 1>&2
+  exit 1
+}
 function Realpath() {
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-SCRIPT="$(dirname "$(Realpath "$0")")/utils.bash"
-if [[ -x "${SCRIPT}" ]]; then
-  # shellcheck source=utils.bash
-  source "${SCRIPT}" "$0"
-else
-  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
+TOOL_PATH="$(Realpath "$0")"
+echo "Attempting to build ${LIBNAME} using ${TOOL_PATH}"
+HERE="$(pwd)"
+if [[ "${HERE}" =~ .*/externs ]]; then
+  cd "${HERE/externs*/}" || Die "Trying to escape externs sub-directory failed"
 fi
+PROJECT_DIR="$(git rev-parse --show-toplevel)" || Die "Not in git repo"
+REPO_DIR="$(basename "${GIT_URL}" .git)"
+BUILD_DIR="build"
+INSTALL_DIR="${PROJECT_DIR}/externs"
+mkdir -p "${INSTALL_DIR}"
+cd "${INSTALL_DIR}" || Die "Unable to enter ${INSTALL_DIR}"
+if [[ -d "${REPO_DIR}/.git" ]]; then
+  git -C "${REPO_DIR}" pull
+else
+  rm -fr "${REPO_DIR}"
+  git clone "${GIT_URL}" || Die "Unable to clone"
+fi
+cd "${REPO_DIR}" || Die "Unable to enter ${REPO_DIR}"
+cmake -B "${BUILD_DIR}" -S . -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" || Die "Unable to configure cmake"
+cmake --build "${BUILD_DIR}" || Die "Failed to compile and link"
+cmake --install build || Die "Failed to install"
+echo "Successfully built ${LIBNAME}"
 
-GetBuildOpts "$0" "$@"
-ConfirmBuildOpts || exit
-
-Create_and_Cd "${SRC}"
-GetSource_and_Cd "${TOOL_SRC}" "${TOOL_URL}"
-
-Generate "${GENERATOR}"
-_do make
-_do make install
-echo "
-${CBLU}
--------------------------------------------------------------------------------
-* Built ${TOOL_SRC} under ${SRC}/${TOOL_SRC}.
-* Installed ${TOOL_SRC} under ${CMAKE_INSTALL_PREFIX}.
--------------------------------------------------------------------------------
-${NONE}
-"
+# vim:nospell
diff --git a/.local/bin/build-gtest b/.local/bin/build-gtest
--- a/.local/bin/build-gtest
+++ b/.local/bin/build-gtest
@@ -1,92 +1,41 @@
 #!/usr/bin/env bash
 #
-# Steps to build and install GoogleTest
-TOOL_NAME="googletest"
-TOOL_INFO='Go to 'https://{:TBS:}' for more information.'
-TOOL_SRC="googletest"
-TOOL_URL="https://{:TBS:}"
-TOOL_VERS=2.3.3
+# Install GoogleTest under current project.
+# IMPORTANT; Must be run inside project git repository.
 
-export TOOL_NAME TOOL_SRC TOOL_URL TOOL_INFO TOOL_VERS
-export SRC BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX
+LIBNAME="GoogleTest"
+GIT_URL="https://github.com/google/googletest.git"
 
-#-------------------------------------------------------------------------------
-# The following is formatted for use with -help
-#|
-#|NAME
-#|----
-#|
-#|  $0 - build and install googletest under externs/ in your project from github source
-#|
-#|SYNOPSIS
-#|--------
-#|
-#|  $0 -help
-#|  $0 [OPTIONS...]
-#|
-#|DESCRIPTION
-#|-----------
-#|
-#|  Downloads, unpacks, builds and installs the latest or specified version of GoogleTest.
-#|
-#|OPTIONS
-#|-------
-#|  --cc=C_COMPILER | CC=C_COMPILER
-#|  --clang
-#|  --cxx=CPP_COMPILER | CXX=CPP_COMPILER
-#|  --debug # developer use
-#|  --gcc
-#|  --install=DIR | -i DIR
-#|  --src=DIR | -s DIR
-#|  --std=N | -std=N
-#|
-
-export SHELL
-SHELL=bash
-
+function Die() {
+  echo "FAILED to build and install ${LIBNAME}! $*" 1>&2
+  exit 1
+}
 function Realpath() {
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-SCRIPT="$(Realpath "$0")"
-SCRIPT="$(dirname "${SCRIPT}")/utils.bash"
-if [[ -x "${SCRIPT}" ]]; then
-  # shellcheck disable=SC1090
-  source "${SCRIPT}" "$0"
-else
-  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
+TOOL_PATH="$(Realpath "$0")"
+echo "Attempting to build ${LIBNAME} using ${TOOL_PATH}"
+HERE="$(pwd)"
+if [[ "${HERE}" =~ .*/externs ]]; then
+  cd "${HERE/externs*/}" || Die "Trying to escape externs sub-directory failed"
 fi
-SetupLogdir "$0"
-
-GetBuildOpts "$0" "$@"
-CMAKE_INSTALL_PREFIX="${GITROOT_DIR}/externs"
-ConfirmBuildOpts || exit
-
-Create_and_Cd "${SRC}"
-Report_info -grn "Obtaining ${TOOL_NAME} source"
-GetSource_and_Cd "${TOOL_SRC}" "${TOOL_URL}"
-
-Report_info -grn "Compiling ${TOOL_NAME}"
-# shellcheck disable=SC2119,SC2312
-Generate | Log
-_do cd "${BUILD_DIR}" || Report_fatal "Unable to enter ${BUILD_DIR}"
-_do make
-
-if [[ -z "${NOINSTALL+x}" ]]; then
-  Report_info -grn "Installing ${TOOL_NAME} to final location"
-  _do make install
-
-  # Optional clean up
-  if [[ "${CLEAN}" == 1 ]]; then
-    Report_info -red "Clean up"
-    cd "${SRC}" || Report_fatal "Unable to enter source directory"
-    # shellcheck disable=SC2312
-    rm -fr "${TOOL_NAME}"* | Log
-  fi
-
-  Report_info -grn "Finished installation of ${TOOL_NAME} into ${CMAKE_INSTALL_PREFIX}"
+PROJECT_DIR="$(git rev-parse --show-toplevel)" || Die "Not in git repo"
+REPO_DIR="$(basename "${GIT_URL}" .git)"
+BUILD_DIR="build"
+INSTALL_DIR="${PROJECT_DIR}/externs"
+mkdir -p "${INSTALL_DIR}"
+cd "${INSTALL_DIR}" || Die "Unable to enter ${INSTALL_DIR}"
+if [[ -d "${REPO_DIR}/.git" ]]; then
+  git -C "${REPO_DIR}" pull
 else
-  Report_info -mag "Stopped shy installing ${TOOL_NAME}"
+  rm -fr "${REPO_DIR}"
+  git clone "${GIT_URL}" || Die "Unable to clone"
 fi
+cd "${REPO_DIR}" || Die "Unable to enter ${REPO_DIR}"
+cmake -B "${BUILD_DIR}" -S . -DCMAKE_INSTALL_PREFIX="${INSTALL_DIR}" || Die "Unable to configure cmake"
+cmake --build "${BUILD_DIR}" || Die "Failed to compile and link"
+cmake --install build || Die "Failed to install"
+echo "Successfully built ${LIBNAME}"
 
 # vim:nospell
