Convert to using utils.bash and better hashbang

diff --git a/.local/bin/build-ag b/.local/bin/build-ag
--- a/.local/bin/build-ag
+++ b/.local/bin/build-ag
@@ -1,12 +1,14 @@
-#!/bin/bash
+#!/usr/bin/env bash
 #
 # Script to build/install Silver searcher, the fastest file searching tool on the planet!
 TOOL="Silver searcher (ag)"
-REPORTING_BASH="$(dirname "$0")/reporting.bash"
-if [[ -f "${REPORTING_BASH}" ]]; then
-  source "${REPORTING_BASH}" "$0"
+
+SCRIPT="$(dirname "$0")/utils.bash"
+if [[ -x "${SCRIPT}" ]]; then
+  # shellcheck source=utils.bash
+  source "${SCRIPT}" "$0"
 else
-  echo "Error: Missing ${REPORTING_BASH}" 1>&2; exit 1
+  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
 fi
 
 LOCAL="${HOME}/.local"
