Updated for public repo.
Signed-off-by: David C Black <david.black@doulos.com>

diff --git a/.local/bin/build-cci b/.local/bin/build-cci
--- a/.local/bin/build-cci
+++ b/.local/bin/build-cci
@@ -1,51 +1,108 @@
 #!/usr/bin/env bash
 #
 # Script to build CCI for SystemC
-TOOL_NAME="SystemC Control, Configuration and Inspection (CCI)"
-TOOL_INFO="Go to 'https://accellera.org/downloads/standards/systemc' for more information."
+TOOL_NAME="cci"
+TOOL_INFO='Go to <https://accellera.org/downloads/standards/systemc> for more information.'
 TOOL_SRC="cci"
-TOOL_URL="git@github.com:OSCI-WG/cci.git"
+TOOL_URL="https://github.com/accellera-official/cci.git"
+TOOL_VERS=1.0.0
+TOOL_CHECKOUT="master"
+
+export TOOL_NAME TOOL_SRC TOOL_URL TOOL_INFO TOOL_VERS TOOL_CHECKOUT TOOL_PATCHES NOINSTALL
+export SYSTEMC_HOME SRC BUILD_DIR CLEAN CMAKE_INSTALL_PREFIX CMAKE_APPLE_SILICON_PROCESSOR
+
+#-------------------------------------------------------------------------------
+# The following is formatted for use with -help
+#|
+#|NAME
+#|----
+#|
+#|  $0 - build and install SystemC CCI from github source
+#|
+#|SYNOPSIS
+#|--------
+#|
+#|  $0 -help
+#|  $0 [OPTIONS...]
+#|
+#|DESCRIPTION
+#|-----------
+#|
+#|  Downloads, unpacks, builds and installs the latest or specified version of SystemC.
+#|
+#|OPTIONS
+#|-------
+#|
+#| The following are all from the `GetBuildOpts` function in `utils.bash`
+#|
+#|  --build-dir=DIR | -bd DIR
+#|  --cc=C_COMPILER | CC=C_COMPILER
+#|  --clang
+#|  --clean
+#|  --cxx=CPP_COMPILER | CXX=CPP_COMPILER
+#|  --debug # developer use
+#|  --doxy
+#|  --gcc
+#|  --help | -h
+#|  --install=DIR | -i DIR
+#|  --not-really | -n
+#|  --no-install
+#|  --no-patch
+#|  --patch[=NAME | -patch [NAME]
+#|  --src=DIR | -s DIR
+#|  --std=N | -std=N
+#|
 
 function Realpath() {
   if [[ $# == 0 ]]; then set - .; fi
   /usr/bin/perl '-MCwd(abs_path)' -le '$p=abs_path(join(q( ),@ARGV));print $p if -e $p' "$*"
 }
 
-SCRIPT="$(dirname $(Realpath "$0"))/utils.bash"
-if [[ -x "${SCRIPT}" ]]; then
-  # shellcheck source=utils.bash
-  source "${SCRIPT}" "$0"
-else
-  echo "Error: Missing ${SCRIPT}" 1>&2; exit 1
+SCRIPTDIR="$(Realpath "$(dirname "$0")"/../bin)"
+if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
+  SCRIPTDIR="$(Realpath "${HOME}"/.local/bin)"
 fi
+if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
+  SCRIPTDIR="$(Realpath "$(dirname "$0")")"
+fi
+if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
+  printf "FATAL: Missing required source file '%s'\n" "${SCRIPTDIR}/utils.bash"
+  exit 1
+fi
+# shellcheck disable=SC2250,SC1091
+source "$SCRIPTDIR/utils.bash"
 
 SetupLogdir "$0"
 
 GetBuildOpts "$0" "$@"
+CMAKE_INSTALL_PREFIX="${SYSTEMC_HOME}"
 ConfirmBuildOpts || exit
 
-Create_and_Cd "${SRC}"
+Create_and_Cd "${SRC}" || exit
+Report_info -grn "Obtaining ${TOOL_NAME} source"
+GetSource_and_Cd "${TOOL_SRC}" "${TOOL_URL}" || exit
 
-# Validate that SystemC exists
-if [[ ! -d "${SYSTEMC_HOME}/include" ]]; then
-  Die "Missing SystemC installation or SYSTEMC_HOME moved"
+Report_info -grn "Building ${TOOL_NAME}"
+# shellcheck disable=SC2119,SC2312
+Configure_tool | Log
+# shellcheck disable=SC2119,SC2312
+Compile_tool   | Log
+
+if [[ -z "${NOINSTALL+x}" ]]; then
+  # shellcheck disable=SC2119,SC2312
+  Install_tool | Log
+
+  # Optional clean up
+  if [[ "${CLEAN}" == 1 ]]; then
+    Report_info -red "Clean up"
+    cd "${SRC}" || Report_fatal "Unable to enter source directory"
+    # shellcheck disable=SC2312
+    rm -fr "${TOOL_SRC}"* | Log
+  fi
+
+  Report_info -grn "Finished installation of ${TOOL_NAME} into ${SYSTEMC_HOME}"
+else
+  Report_info -mag "Stopped shy installing ${TOOL_NAME}"
 fi
-if [[ ! -d "${CCI_HOME}/src" ]]; then
-  Die "Missing CCI source or CCI_HOME moved"
-fi
 
-GitClone_and_Cd "${TOOL_SRC}" "${TOOL_URL}"
-
-if [[ "${GENERATE_DOCS}" == 1 ]]; then
-  Report_info "Build documentation"
-  cd "${CCI_HOME}/doc"
-  doxygen cci_doxygen_api_ref.conf
-  doxygen cci_doxygen_examples.conf
-  #doxygen cci_doxygen_gs_impl_ref.conf
-fi
-
-Report_info "Compile library"
-cd "${CCI_HOME}/src"
-make V=1
-
-Report_info "Finished installation of CCI into ${CCI_HOME}"
+# vim:nospell
