Add help
Support -h or --help with descriptive text formatted for markdown marked with HELPTEXT.

Signed-off-by: David C Black <david.black@doulos.com>

diff --git a/.local/bin/build-cmake b/.local/bin/build-cmake
--- a/.local/bin/build-cmake
+++ b/.local/bin/build-cmake
@@ -2,39 +2,42 @@
 #
 # Install the latest or specified version of cmake
 
-#-------------------------------------------------------------------------------
-# The following is formatted for use with -help
-#|
-#|NAME
-#|----
-#|
-#|  $0 - build and install cmake from source
-#|
-#|SYNOPSIS
-#|--------
-#|
-#|  $0 -help
-#|  $0 [-clean] [-debug] [-git|-wget|-curl] [-install=DIR] [-src=SRCDIR]
-#|
-#|DESCRIPTION
-#|-----------
-#|
-#|  Downloads, unpacks, builds and installs the latest or specified version of cmake.
-#|
+if [[ "$!" =~ ^-{1,2}h(elp)?$ ]]; then
+  cat <<'HELPTEXT'
+Name
+----
+
+  build-cmake - build and install cmake from source
+
+Synopsis
+--------
+
+build-cmake --help|-h # produces this text
+build-cmake [-clean] [-debug] [-git|-wget|-curl] [-install=DIR] [-src=SRCDIR]
+
+Description
+-----------
+
+Downloads, unpacks, builds and installs the latest or specified version of [cmake](https://cmake.org/documentation/).
+
+HELPTEXT
+exit 0;
+fi
+
 
 #-------------------------------------------------------------------------------
 # Make things more visible in the output
 
 SCRIPTDIR="$(Realpath "$(dirname "$0")"/../bin)"
 if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath "${HOME}"/.local/bin)"
+SCRIPTDIR="$(Realpath "${HOME}"/.local/bin)"
 fi
 if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  SCRIPTDIR="$(Realpath "$(dirname "$0")")"
+SCRIPTDIR="$(Realpath "$(dirname "$0")")"
 fi
 if [[ ! -r "${SCRIPTDIR}/utils.bash" ]]; then
-  printf "FATAL: Missing required source file '%s'\n" "${SCRIPTDIR}/utils.bash"
-  exit 1
+printf "FATAL: Missing required source file '%s'\n" "${SCRIPTDIR}/utils.bash"
+exit 1
 fi
 # shellcheck disable=SC2250,SC1091
 source "$SCRIPTDIR/utils.bash"
@@ -49,86 +52,82 @@ MAJVERS=3
 MINVERS=22
 DOTVERS=0
 if [[ "${TYPE}" == "" ]]; then
-  TYPE=-wget # use -git or -wget or -curl
+TYPE=-wget # use -git or -wget or -curl
 fi
 
 #-------------------------------------------------------------------------------
 # Scan command-line for options
 #-------------------------------------------------------------------------------
 while [[ $# != 0 ]]; do
-  case "$1" in
-  -h|-help)
-    /usr/bin/perl -ne '$p = $ARGV; $p =~ s{.*/}{}; if ( $_ =~ s{^#\|}{} ) { $_ =~ s{\$0}{$p}; print; }' "$0";
-    exit 0;
-    ;;
-  -git|-wget|-curl)
-    TYPE="$1";
-    shift;
-    ;;
-  -d|-debug|--debug)
-    DEBUG=1;
-    shift;
-    ;;
-  --clean|-clean)
-    CLEAN=1;
-    shift;
-    ;;
-  -i|--install=*)
-    if [[ "$1" != '-i' ]]; then
-      CMAKE_INSTALL_PREFIX="${1//*=/}"
-    elif [[ $# -gt 1 && -d "$2" ]]; then
-      CMAKE_INSTALL_PREFIX="$2"
-      shift
-    else
-      Report_fatal "Need directory argument for --install"
-    fi
-    shift;
-    ;;
-  -s|--src=*)
-    if [[ "$1" != '-s' ]]; then
-      SRC="${1//*=/}"
-    elif [[ $# -gt 1 && -d "$2" ]]; then
-      SRC="$2"
-      shift
-    else
-      Report_fatal "Need directory argument for --src"
-    fi
-    shift;
-    ;;
-  *)
-    Report_fatal "ERROR: Unkhown option $1";
-    ;;
-  esac
+case "$1" in
+-git|-wget|-curl)
+  TYPE="$1";
+  shift;
+  ;;
+-d|-debug|--debug)
+  DEBUG=1;
+  shift;
+  ;;
+--clean|-clean)
+  CLEAN=1;
+  shift;
+  ;;
+-i|--install=*)
+  if [[ "$1" != '-i' ]]; then
+    CMAKE_INSTALL_PREFIX="${1//*=/}"
+  elif [[ $# -gt 1 && -d "$2" ]]; then
+    CMAKE_INSTALL_PREFIX="$2"
+    shift
+  else
+    Report_fatal "Need directory argument for --install"
+  fi
+  shift;
+  ;;
+-s|--src=*)
+  if [[ "$1" != '-s' ]]; then
+    SRC="${1//*=/}"
+  elif [[ $# -gt 1 && -d "$2" ]]; then
+    SRC="$2"
+    shift
+  else
+    Report_fatal "Need directory argument for --src"
+  fi
+  shift;
+  ;;
+*)
+  Report_fatal "ERROR: Unkhown option $1";
+  ;;
+esac
 done
 
 if [[ "${DEBUG}" == 1 ]]; then
-  echo "DEBUG=${DEBUG}"
-  echo "CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
-  echo "MAJVERS=${MAJVERS}"
-  echo "MINVERS=${MINVERS}"
-  echo "DOTVERS=${DOTVERS}"
-  echo "NPROC=${NPROC}"
+echo "DEBUG=${DEBUG}"
+echo "CMAKE_INSTALL_PREFIX=${CMAKE_INSTALL_PREFIX}"
+echo "MAJVERS=${MAJVERS}"
+echo "MINVERS=${MINVERS}"
+echo "DOTVERS=${DOTVERS}"
+echo "NPROC=${NPROC}"
 fi
 
 #-------------------------------------------------------------------------------
 Report_info "Setup source directory"
 if [[ -n ${SRC} && -d "${SRC}" ]]; then
-  echo "Using SRC=${SRC}"
+echo "Using SRC=${SRC}"
 fi
 CWD="$(pwd)"
 if [[ -v APPS ]]; then
-  SRC="${APPS}/src"
+SRC="${APPS}/src"
 elif [[ "${HOME}" == "${CWD}" ]]; then
-  SRC="${HOME}/.local/src"
+SRC="${HOME}/.local/src"
 else
-  SRC="$(pwd)/src"
+SRC="$(pwd)/src"
 fi
 mkdir -p "${SRC}" || Report_fatal "Failed to find/create ${SRC} directory"
 
 #-------------------------------------------------------------------------------
 # Determine installation directory
 if [[ ! -v CMAKE_INSTALL_PREFIX ]]; then
-  CMAKE_INSTALL_PREFIX="$(dirname "${SRC}")"
+CMAKE_INSTALL_PREFIX="$(dirname "${SRC}")"
 fi
 export CMAKE_INSTALL_PREFIX
 
@@ -148,10 +147,10 @@ if [[ "${TYPE}" == "-git" ]]; then
 #   ####  ###   #                                                                
 #
 ###############################################################################
- 
-  echo "Cloning cmake"
-  git clone https://gitlab.kitware.com/cmake/cmake.git  || Report_fatal "Failed to clone"
-  cd cmake || Report_fatal "Unable to enter repo"
+
+echo "Cloning cmake"
+git clone https://gitlab.kitware.com/cmake/cmake.git  || Report_fatal "Failed to clone"
+cd cmake || Report_fatal "Unable to enter repo"
 
 else
 ###############################################################################
@@ -165,23 +164,23 @@ else
 #   ## ##   ###   ###     #    |     ####   ##### #      ###            
 #
 ###############################################################################
-  FULL_VERS=${MAJVERS}.${MINVERS}.${DOTVERS}
-  CMAKE_TARBALL="cmake-${FULL_VERS}.tar.gz"
-  URL="https://cmake.org/files/v${MAJVERS}.${MINVERS}/${CMAKE_TARBALL}"
-  echo "Fetching cmake"
-  # Assumed to be under latest; otherwise, use v$MAJOR.$MINOR
-  if [[ "${TYPE}" == "-wget" ]]; then
-    echo "% wget ${URL}"
-    wget "${URL}" || Report_fatal "Failed to download cmake ${URL}"
-  else
-    echo "% curl -output ${CMAKE_TARBALL} ${URL}"
-    curl -output "${CMAKE_TARBALL}" "${URL}" || Report_fatal "Failed to download from ${URL}"
-  fi
-  echo "Expanding cmake tarball"
-  echo "% tar zxvf cmake-${FULL_VERS}.tar.gz"
-  tar zxvf "cmake-${FULL_VERS}.tar.gz" || Report_fatal "Failed to extract cmake-${FULL_VERS}.tar.gz"
-  echo "% cd cmake-${FULL_VERS}"
-  cd "cmake-${FULL_VERS}" || Report_fatal "Unable to enter source directory"
+FULL_VERS=${MAJVERS}.${MINVERS}.${DOTVERS}
+CMAKE_TARBALL="cmake-${FULL_VERS}.tar.gz"
+URL="https://cmake.org/files/v${MAJVERS}.${MINVERS}/${CMAKE_TARBALL}"
+echo "Fetching cmake"
+# Assumed to be under latest; otherwise, use v$MAJOR.$MINOR
+if [[ "${TYPE}" == "-wget" ]]; then
+  echo "% wget ${URL}"
+  wget "${URL}" || Report_fatal "Failed to download cmake ${URL}"
+else
+  echo "% curl -output ${CMAKE_TARBALL} ${URL}"
+  curl -output "${CMAKE_TARBALL}" "${URL}" || Report_fatal "Failed to download from ${URL}"
+fi
+echo "Expanding cmake tarball"
+echo "% tar zxvf cmake-${FULL_VERS}.tar.gz"
+tar zxvf "cmake-${FULL_VERS}.tar.gz" || Report_fatal "Failed to extract cmake-${FULL_VERS}.tar.gz"
+echo "% cd cmake-${FULL_VERS}"
+cd "cmake-${FULL_VERS}" || Report_fatal "Unable to enter source directory"
 fi
 
 Report_info "Building cmake"
@@ -197,8 +196,8 @@ make install
 
 cd "${SRC}" || Report_fatal "Unable to enter source directory"
 if [[ "${CLEAN}" == 1 ]]; then
-  Report_info "Clean up"
-  rm -fr cmake*
+Report_info "Clean up"
+rm -fr cmake*
 fi
 
 cd || Report_fatal "Unable to return to home"
