Change to use _C() instead of environment variables

diff --git a/.local/bin/mkbin b/.local/bin/mkbin
--- a/.local/bin/mkbin
+++ b/.local/bin/mkbin
@@ -1,5 +1,7 @@
 #!/bin/bash
 
+# shellcheck disable=SC2312
+
 function mkbin_help()
 {
   cat <<'DOCUMENTATION'
@@ -34,28 +36,100 @@ OPTION                | DESCRIPTION
 DOCUMENTATION
 }
 
+#-------------------------------------------------------------------------------
+function _C()
+{
+  export NOCOLOR
+  if [[ ${NOCOLOR} == 1 ]]; then
+    return
+  fi
+  if [[ $# == 0 ]]; then set none; fi
+  export COLOR_SET COLOR_FG
+  local ESC PRF
+  if [[ -z "${COLOR_SET}" ]]; then # default
+    COLOR_SET=10
+  fi
+  if [[ -z "${COLOR_FG}" ]]; then # default
+    COLOR_FG=1
+  fi
+  ESC=""
+  for arg in "$@"; do
+    test -z "${arg}" && continue
+    if [[ ${COLOR_FG} == 1 ]]; then
+      case ${COLOR_SET} in
+        2)  PRF="3"  ;;
+        10) PRF="9"  ;;
+        *)  return 1 ;;
+      esac
+    else
+      case ${COLOR_SET} in
+        2)  PRF="4"  ;;
+        10) PRF="10" ;;
+        *) return 1  ;;
+      esac
+    fi
+    case "${arg}" in
+      dflt|default)    COLOR_SET=2 ; COLOR_FG=1 ;;
+      fg|foreground)   COLOR_FG=1 ;;
+      bg|background)   COLOR_FG=0 ;;
+      bright)          COLOR_SET=10 ;;
+      norm|normal)     COLOR_SET=2 ;;
+      -|none)          echo -n "${ESC}[0m" ; COLOR_FG=1 ;;
+      bold)            echo -n "${ESC}[1m" ;;
+      ubld|nobold)     echo -n "${ESC}[21m" ;;
+      dark)            echo -n "${ESC}[2m" ;;
+      udrk|nodark)     echo -n "${ESC}[22m" ;;
+      undr|under*)     echo -n "${ESC}[4m" ;;
+      blnk|blink)      echo -n "${ESC}[5m" ;;
+      noun*)           echo -n "${ESC}[24m" ;;
+      nblk|noblink)    echo -n "${ESC}[25m" ;;
+      rev*)            echo -n "${ESC}[8m" ;;
+      invs|invi*)      echo -n "${ESC}[8m" ;;
+      unvs|visi*)      echo -n "${ESC}[27m" ;;
+      blk|black)       echo -n "${ESC}[${PRF}0m" ;;
+      red)             echo -n "${ESC}[${PRF}1m" ;;
+      grn|green)       echo -n "${ESC}[${PRF}2m" ;;
+      ylw|yellow)      echo -n "${ESC}[${PRF}3m" ;;
+      blu|blue)        echo -n "${ESC}[${PRF}4m" ;;
+      mag|magenta)     echo -n "${ESC}[${PRF}5m" ;;
+      cyn|cyan)        echo -n "${ESC}[${PRF}6m" ;;
+      wht|white)       echo -n "${ESC}[${PRF}7m" ;;
+      *)               return 1 ;;
+    esac
+  done
+  echo ""
+}
 
+
+#-------------------------------------------------------------------------------
 function Regex
 {
   perl -e 'if ($ARGV[1]=~m/$ARGV[2]/){exit 0;}else{exit 1;}' - "$1" "$2"
 }
 
-export BOLD CRED CGRN NONE
 
 function Report_error()
 {
-  echo "${BOLD}${CRED}Error:${NONE} $*" 1>&2
+  local NONE
+  NONE="$(_C none)"
+  echo "$(_C bold bright red)Error:$(_C none) $*" 1>&2
 }
 
 function Verbose_info()
 {
+  local NONE
+  NONE="$(_C none)"
   if [[ "$1" != 1 ]]; then return; fi
   shift
-  echo "${BOLD}${CGRN}Info:${NONE} $*"
+  echo "$(_C bold bright green)Info:${NONE} $*"
 }
 
+#-------------------------------------------------------------------------------
 function Mkbin()
 {
+  local CRED NONE
+  CRED="$(_C bright red)"
+  NONE="$(_C none)"
   local HASHBANG DIRECTORY EDIT SCRIPT SCRIPT_NAME SCRIPT_PATH
   local OPTION CMNT KIND IS_NEW ADD_TAIL ADD_UTILS FIRST_LINE V N
   ADD_TAIL=0
