Update to latest

diff --git a/.local/apps/templates/sc-project/lxNAMExr/extern/bin/build b/.local/apps/templates/sc-project/lxNAMExr/extern/bin/build
--- a/.local/apps/templates/sc-project/lxNAMExr/extern/bin/build
+++ b/.local/apps/templates/sc-project/lxNAMExr/extern/bin/build
@@ -1,9 +1,10 @@
 #!/usr/bin/env bash
 # vim:syntax=bash
 #
-BUILD_TOOL_VERSION=1.6
+BUILD_TOOL_VERSION=1.10
 BUILD_TOOL_NAME="build"
 export BUILD_TOOL_NAME
+export BUILDRC
 
 function Die() { echo "FAILED to build! $*" 1>&2; exit 1; }
 
@@ -40,9 +41,9 @@ This script was written to simplify using _cmake_ and educate along the way. It 
 
 ```bash
 clean -a # OPTIONAL
-cmake -B build -DCMAKE_BUILD_TYPE=Debug
-cmake --build build --config Debug
-ctest --test-dir build -C Debug -VV # OPTIONAL -OR- run
+cmake -B BUILD -DCMAKE_BUILD_TYPE=Debug
+cmake --build BUILD --config Debug
+ctest --test-dir BUILD -C Debug -VV # OPTIONAL -OR- run
 ```
 If you're skeptical, just run with the `-n` option.
 
@@ -54,16 +55,18 @@ IMPORTANT: This should be run at the top of the project where the CMakeLists.txt
 | ------           | -----------
 | -help            | Display this text (or -h)
 | -n               | Don not actually do anything except show commands that would have been done
-| -B DIR           | Name of build directory -- defaults to \"build\"
+| -B BLD_DIR       | Name of the build directory -- defaults to \"BUILD\"
 | -C DIR           | Change to specified directory before doing anything else
 | -clean           | Remove all build files and other output bits
 | -DVAR=VAL        | Specify a configuration definition (i.e., passed to cmake -B)
 | -G "GEN"         | Specify generator (defaults to Ninja if available)
+| -gcc             | Use GNU compiler chain (i.e., g++ and gcc)
 | -gdb             | Run under gdb
 | -info            | Output information to help debug CMakeLists.txt etc.
 | -install [DIR]   | When done building, install in DIR or PREFIX directory
 | -list-extensions | See EXTENSIONS description following.
 | -lldb            | Run under lldb
+| -llvm            | Use LLVM compiler chain (i.e., clang++ and clang)
 | --loadrc=FILE    | Load switches from FILE
 | -noisy           | Some extra info is displayed
 | -norc            | Ignore .buildrc
@@ -82,6 +85,7 @@ IMPORTANT: This should be run at the top of the project where the CMakeLists.txt
 | -sq              | Squeeze out blank lines from test
 | -std=NN          | Specify C++ standard version
 | -t TGT           | Passed to cmake to specify the target (TGT) and limit ctest
+| -toolchain PATH  | Specify a toolchain for cmake (cmake/toolchain-${NAME}.cmake must exist)
 | -test            | When done building, run the tests verbosely unless -q supplied
 | -type BT         | Select the cmake build type with BT: Debug (default), RelWithDebInfo, Release, or MinSizeRel
 | -verbose         | Adds more information to output. Opposite of quiet.
@@ -100,13 +104,17 @@ For specifics on each build-TOOL or build-LIBRARY try \`build-COMMAND --help\`.
 
 ## DEFAULT OPTIONS
 
-If a the file ~/.buildrc or ./.buildrc exists, their contents will be used for initial command-line options. It will be as if invoked with:
+If a the file `~/.buildrc` or `./.buildrc` exists, their contents will be used for initial command-line options.
+
+Comments (#) and blank lines are allowed and ignored.
+
+If the environment variable `BULDRC` exists, it will be used as command-line options following the above files.
+
+Effectively, the above describes:
 
 ```bash
-build "$(cat ~/.buildrc ./.buildrc)" "$@"
+build "$(cat ~/.buildrc ./.buildrc)" "${BUILDRC}" "$@"
 ```
-
-Except that comments and blank lines are removed.
 
 ## EXAMPLES
 
@@ -127,11 +135,12 @@ function Confirm()
 {
   local REPLY
   while true; do
-    printf "%s" "$1 "
+    printf "%s" "$1 (yes|no|y|n|abort) "
     read -r REPLY
     case "${REPLY}" in
       y|Y|yes) return 0 ;;
       n|N|no) return 1 ;;
+      abort) exit 1 ;;
       *) REPLY=""; echo "Must reply with 'y' or 'n'" ;;
     esac
   done
@@ -139,15 +148,21 @@ function Confirm()
 
 function Build()
 {
+  export BUILDRC
   # Handle extensions
   #------------------------------------------------------------------------------
   if [[ $# -ge 1 ]]; then
     # Check first argument for possible build-TARGET
     case "$1" in
       clean)
-        echo "Warning: Assume you meant -clean?"
-        shift
-        set - -clean "$@"
+        # shellcheck disable=SC2310
+        if Confirm "Did you mean -clean?"; then
+          shift
+          set - -clean "$@"
+        else
+          echo "Ignoring"
+          shift
+        fi
         ;;
       [A-Za-z]*)
         if [[ "$1" =~ ^[A-Za-z][A-Za-z0-9_]+$ ]]; then
@@ -180,7 +195,7 @@ function Build()
 
   # If not yet defined
   if [[ -z "${SCRIPTS_DIR}" ]]; then
-    # Try the directory where build is located
+    # Try the directory where the build script is located
     SCRIPTS_DIR="$(dirname "${BUILD_TOOL_DIR}")/scripts"
   fi
   if [[ ! -f "${SCRIPTS_DIR}/Essential-IO" ]]; then
@@ -196,7 +211,7 @@ function Build()
   # Add .buildrc if present
   #------------------------------------------------------------------------------
   local NORC RC_PERLSCRIPT
-  local -a BUILDRC=()
+  local -a BUILDRC_ARGS=()
   local RCARG
   local -a RCARGS=()
   NORC=0
@@ -216,19 +231,24 @@ function Build()
   if [[ ${NORC} == 0 ]]; then
     if [[ -r ~/.buildrc ]]; then
       # shellcheck disable=SC2207
-      BUILDRC+=( $(perl -pe "${RC_PERLSCRIPT}" ~/.buildrc) )
+      BUILDRC_ARGS+=( $(perl -pe "${RC_PERLSCRIPT}" ~/.buildrc) )
     fi
     if [[ -r "./.buildrc" ]]; then
       # shellcheck disable=SC2207
-      BUILDRC+=( $(perl -pe "${RC_PERLSCRIPT}" "./.buildrc") )
+      BUILDRC_ARGS+=( $(perl -pe "${RC_PERLSCRIPT}" "./.buildrc") )
     fi
     RCARGS=()
-    for RCARG in "${BUILDRC[@]}"; do
+    for RCARG in "${BUILDRC_ARGS[@]}"; do
       if [[ "${RCARG}" =~ ^\ *$ ]]; then
-        continue;
+        continue; # Skip blank lines
       fi
       RCARGS+=( "${RCARG}" )
     done
+    if [[ -n "${BUILDRC}" ]]; then
+      for RCARG in "${BUILDRC[@]}"; do
+        RCARGS+=( "${RCARG}" )
+      done
+    fi
     RCARGS+=( "$@" )
     set - "${RCARGS[@]}"
     Report_info -f "build ${RCARGS[*]}"
@@ -240,7 +260,7 @@ function Build()
   local SRC_DIR BLD_DIR CLEAN DEBUG INSTALL PREFIX OPTS_SEP QUIET NOISY SQUEEZE HAS_NINJA
   SRC_DIR="."
   CMAKE_BUILD_TYPE="Debug"
-  BLD_DIR="build"
+  BLD_DIR="BUILD"
   SUBPROJ_DIR="$(pwd)"
   HAS_NINJA="$(command -v ninja)"
   if [[ -n "${HAS_NINJA}" ]]; then
@@ -274,7 +294,7 @@ function Build()
   # Scan for command-line options
   #------------------------------------------------------------------------------
   export WORKTREE_DIR
-  WORKTREE_DIR="" ;#< Do not allow environment in
+  WORKTREE_DIR="$(git rev-parse --show-toplevel)" || Die "Not in git repo"
 
   local -a ORIG_ARGS=()
   ORIG_ARGS=( "$@" )
@@ -286,6 +306,36 @@ function Build()
       shift
       Build_help
       return 0
+    #...........................................................................
+    elif [[ "$1" =~ ^-(toolchain)|(tc)$ ]]; then
+      if [[ $# -gt 1 && "$2" =~ ^[a-zA-Z] ]]; then
+        shift
+        local TOOLCHAIN
+        TOOLCHAIN="$(Realpath "$1")"
+        echo "Debug: TOOLCHAIN=${TOOLCHAIN}"
+        if [[ -z "${TOOLCHAIN}" ]]; then
+          TOOLCHAIN="$(Realpath "${WORKTREE_DIR}/cmake/toolchain-$1.cmake")"
+          if [[ -z "${TOOLCHAIN}" ]]; then
+            Report_fatal "Missing $1"
+          fi
+        fi
+        echo "Debug: TOOLCHAIN=${TOOLCHAIN}"
+        CONFIG_OPTS=("${CONFIG_OPTS[@]}" "-DCMAKE_TOOLCHAIN_FILE='${TOOLCHAIN}'")
+      else
+        Report_fatal "-toolchain requires an argument starting with a letter"
+      fi
+    #...........................................................................
+    elif [[ "$1" =~ ^-(gcc)|(GCC)|(gnu)|(GNU)$ ]]; then
+      export CXX CC
+      CXX="$(command -v g++)"
+      CC="$(command -v gcc)"
+      CONFIG_OPTS=("${CONFIG_OPTS[@]}" "-DCMAKE_CXX_COMPILER=${CXX}" "-DCC=${CC}")
+    #...........................................................................
+    elif [[ "$1" =~ ^-(llvm)|(LLVM)|(clang)$ ]]; then
+      export CXX CC
+      CXX="$(command -v clang++)"
+      CC="$(command -v clang)"
+      CONFIG_OPTS=("${CONFIG_OPTS[@]}" "-DCMAKE_CXX_COMPILER=${CXX}" "-DCC=${CC}")
     #...........................................................................
     elif [[ "$1" == "-B" ]]; then
       if [[ $# -lt 2 ]]; then
@@ -308,7 +358,7 @@ function Build()
         shift
       fi
     #...........................................................................
-    elif [[ "$1" =~ ^-D[a-zA-Z_]+= ]]; then
+    elif [[ "$1" =~ ^-D[a-zA-Z_][a-zA-Z_0-9]*=? ]]; then
       CONFIG_OPTS=("${CONFIG_OPTS[@]}" "$1")
     #...........................................................................
     elif [[ "$1" =~ ^[a-zA-Z_][a-zA-Z_0-9]*= ]]; then
@@ -410,9 +460,9 @@ function Build()
         continue
       fi
       # shellcheck disable=SC2207
-      BUILDRC=( $(perl -pe "${RC_PERLSCRIPT}" "${RCFILE}") )
+      BUILDRC_ARGS=( $(perl -pe "${RC_PERLSCRIPT}" "${RCFILE}") )
       RCARGS=()
-      for RCARG in "${BUILDRC[@]}"; do
+      for RCARG in "${BUILDRC_ARGS[@]}"; do
         if [[ "${RCARG}" =~ ^\ *$ ]]; then
           continue;
         fi
@@ -425,7 +475,7 @@ function Build()
       Report_info -f -blu "
  -------------------------------------------------------------------------------
  ${BUILD_TOOL_NAME} version ${BUILD_TOOL_VERSION}
- Copyright 2023 by Doulos Inc. All rights reserved.
+ Copyright 2024 by Doulos Inc. All rights reserved.
 
  Licensed under the Apache License, Version 2.0 (the \"License\");
  you may not use this file except in compliance with the License.
@@ -638,8 +688,8 @@ function Build()
   #------------------------------------------------------------------------------
   if [[ ${CLEAN} == 1 ]]; then
     # Preserve log
-    local TEMP_LOG
-    TEMP_LOG="$(mktemp -t build.XXXXXX.log)"
+    local TEMP_LOG BLD_NAM="${BLD_DIR/\//_}"
+    TEMP_LOG="$(mktemp -t "${BLD_NAM}.XXXXXX.log")"
     Report_info -f "Cleaning ${SUBPROJ_DIR}"
     _do -n rm -fr "${BLD_DIR}"
     mv "${BLD_DIR}/${BUILD_LOG}" "${TEMP_LOG}"
@@ -677,7 +727,7 @@ function Build()
       break
     fi
   done
-  mapfile -d '' TARGETS < <( "${FIND}" "${BLD_DIR}" -type f -executable ! -path '*/CMake*/*' -print0 || true )
+  mapfile -d '' TARGETS < <( "${FIND}" "./${BLD_DIR}" -type f -executable ! -path '*/CMake*/*' -print0 || true )
 
   #------------------------------------------------------------------------------
   if [[ "${ACTION}" == "list" ]]; then
@@ -686,7 +736,7 @@ function Build()
         Report_warning "No targets found? Did you build successfully?"
         ;;
       1) 
-        Report_info -f "Targets is ${TARGETS[0]}"
+        Report_info -f "Target is ${TARGETS[0]}"
         ;;
       *)
         Report_info -f "Targets are:"
@@ -720,14 +770,14 @@ function Build()
       Report_fatal "Not sure what to debug!"
     fi
   elif [[ "${ACTION}" == "run" ]]; then
-    Report_info -f "Running ${SUBPROJ_DIR}"
+    Report_info -f "Running in ${SUBPROJ_DIR}"
     if [[ ${#TARGETS[@]} -gt 0 ]]; then
       for EXECUTABLE in "${TARGETS[@]}"; do
         # shellcheck disable=SC2086,SC2312
         ( _do "${EXECUTABLE}" "${TEST_OPTS[@]}" ) 2>&1 | tee run.log
       done
     else
-      Report_fatal "Not sure what to run! Probably sub-directories. Please run manually. Look for executable under build."
+      Report_fatal "Not sure what to run! Probably sub-directories. Please run manually. Look for executable under ${BLD_DIR}."
     fi
   elif [[ "${ACTION}" == "test" ]]; then
     Report_info -f "Testing ${SUBPROJ_DIR}"
